server:
  port: 9000
spring:
  application:
    name: consumer
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
    virtual-host: /
    listener:
      direct:
        prefetch: 10
      simple:
        prefetch: 10

springdoc:
  show-actuator: false
  swagger-ui:
    doc-expansion: none