server:
  port: 8000
spring:
  application:
    name: producer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

springdoc:
  show-actuator: false
  swagger-ui:
    doc-expansion: none